version: '3.4'

services:
  pubsubrabbitmq.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"

  pubsubrabbitmq.notifications:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    ports:
      - "8082:8082"


  pubsubrabbitmq.sales:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8083
    ports:
      - "8083:8083"